Repository prgrms-be-devcourse/BE-04-PoMin-Owner, pull requests merged in 2023-09, with the labels that each got.

#11 [POM-57] feat: 엔티티 클래스 수정
  src/main/java/com/ray/pominowner/global/domain/PhoneNumber.java
  src/main/java/com/ray/pominowner/orders/domain/Order.java
  src/main/java/com/ray/pominowner/orders/domain/OrderMenu.java
Labels: FEAT

#12 [POM-50] feat: 필수 정보 통한 가게 등록 구현
  build.gradle
  src/main/java/com/ray/pominowner/global/vo/CategoryCache.java
  src/main/java/com/ray/pominowner/store/controller/StoreController.java
  src/main/java/com/ray/pominowner/store/controller/dto/StoreRegisterRequest.java
  src/main/java/com/ray/pominowner/store/domain/RequiredStoreInfo.java
  src/main/java/com/ray/pominowner/store/domain/Store.java
  src/main/java/com/ray/pominowner/store/repository/StoreRepository.java
  src/main/java/com/ray/pominowner/store/service/StoreService.java
  src/test/java/com/ray/pominowner/store/controller/StoreControllerTest.java
Labels: FEAT

#10 [POM-60] feat: 결제, 정산 엔티티 구현
  src/main/java/com/ray/pominowner/global/util/ExceptionMessage.java
  src/main/java/com/ray/pominowner/global/util/Validator.java
  src/main/java/com/ray/pominowner/payment/domain/PGType.java
  src/main/java/com/ray/pominowner/payment/domain/Payment.java
  src/main/java/com/ray/pominowner/payment/domain/PaymentStatus.java
  src/main/java/com/ray/pominowner/settlement/domain/Fee.java
  src/main/java/com/ray/pominowner/settlement/domain/PayOut.java
  src/main/java/com/ray/pominowner/settlement/domain/Sales.java
  src/main/java/com/ray/pominowner/settlement/domain/Settlement.java
  src/main/resources/dev/application-dev.yml
Labels: FEAT

#13 [POM-60] 결제, 정산 엔티티 테스트
  src/main/java/com/ray/pominowner/global/util/ExceptionMessage.java
  src/main/java/com/ray/pominowner/settlement/domain/PayOut.java
  src/main/java/com/ray/pominowner/settlement/domain/Sales.java
  src/main/java/com/ray/pominowner/settlement/domain/Settlement.java
  src/test/java/com/ray/pominowner/payment/domain/PaymentTest.java
  src/test/java/com/ray/pominowner/settlement/domain/FeeTest.java
  src/test/java/com/ray/pominowner/settlement/domain/PayOutTest.java
  src/test/java/com/ray/pominowner/settlement/domain/SalesTest.java
  src/test/java/com/ray/pominowner/settlement/domain/SettlementTest.java
Labels: FEAT

#14 [POM-57] 주문 서비스 구현, 서비스 테스트 생성
  src/main/java/com/ray/pominowner/orders/domain/Order.java
  src/main/java/com/ray/pominowner/orders/repository/OrderRepository.java
  src/main/java/com/ray/pominowner/orders/service/OrderService.java
  src/main/java/com/ray/pominowner/orders/service/ReceiptNumberGenerator.java
  src/test/java/com/ray/pominowner/orders/service/OrderServiceTest.java
Labels: FEAT

#15 [POM-50] feat: 카테고리 등록(선택) 기능 구현
  src/main/java/com/ray/pominowner/global/vo/CategoryCache.java
  src/main/java/com/ray/pominowner/payment/domain/PGType.java
  src/main/java/com/ray/pominowner/payment/domain/Payment.java
  src/main/java/com/ray/pominowner/store/controller/StoreController.java
  src/main/java/com/ray/pominowner/store/controller/dto/CategoryRequest.java
  src/main/java/com/ray/pominowner/store/domain/Category.java
  src/main/java/com/ray/pominowner/store/domain/RequiredStoreInfo.java
  src/main/java/com/ray/pominowner/store/domain/Store.java
  src/main/java/com/ray/pominowner/store/domain/StoreCategory.java
  src/main/java/com/ray/pominowner/store/repository/StoreCategoryRepository.java
  src/main/java/com/ray/pominowner/store/service/StoreCategoryService.java
  src/main/java/com/ray/pominowner/store/service/StoreService.java
  src/main/java/com/ray/pominowner/store/service/StoreServiceValidator.java
  src/main/java/com/ray/pominowner/store/service/vo/CategoryConverter.java
  src/test/java/com/ray/pominowner/settlement/domain/FeeTest.java
  src/test/java/com/ray/pominowner/settlement/domain/SettlementTest.java
  src/test/java/com/ray/pominowner/store/StoreTestFixture.java
  src/test/java/com/ray/pominowner/store/controller/StoreControllerTest.java
  src/test/java/com/ray/pominowner/store/domain/RequiredStoreInfoTest.java
  src/test/java/com/ray/pominowner/store/domain/StoreCategoryTest.java
  src/test/java/com/ray/pominowner/store/domain/StoreTest.java
  src/test/java/com/ray/pominowner/store/service/StoreServiceTest.java
Labels: FEAT

#18 [POM-50] feat: 사업자등록번호 Long -> String 변경
  src/main/java/com/ray/pominowner/store/controller/dto/StoreRegisterRequest.java
  src/main/java/com/ray/pominowner/store/domain/RequiredStoreInfo.java
  src/main/java/com/ray/pominowner/store/domain/Store.java
  src/test/java/com/ray/pominowner/store/StoreTestFixture.java
  src/test/java/com/ray/pominowner/store/controller/StoreControllerTest.java
  src/test/java/com/ray/pominowner/store/domain/RequiredStoreInfoTest.java
Labels: FEAT

#19 [POM-57] OrderController 구현, 테스트 코드 작성
  src/main/java/com/ray/pominowner/orders/controller/OrderController.java
  src/main/java/com/ray/pominowner/orders/controller/dto/ApproveOrderResponse.java
  src/main/java/com/ray/pominowner/orders/controller/dto/ReceiveOrderRequest.java
  src/main/java/com/ray/pominowner/orders/controller/dto/RejectOrderResponse.java
  src/main/java/com/ray/pominowner/orders/domain/Order.java
  src/test/java/com/ray/pominowner/orders/controller/OrderControllerTest.java
Labels: FEAT

#23 [POM-77] feat: Order 엔티티에 payment 연관성 추가, controller 변경
  src/main/java/com/ray/pominowner/orders/controller/OrderController.java
  src/main/java/com/ray/pominowner/orders/controller/dto/ReceiveOrderRequest.java
  src/main/java/com/ray/pominowner/orders/controller/dto/RejectOrderResponse.java
  src/main/java/com/ray/pominowner/orders/domain/Order.java
  src/test/java/com/ray/pominowner/orders/controller/OrderControllerTest.java
Labels: FEAT

#30 [POM-84] feat: 주문 거절 시 결제 취소
  src/main/java/com/ray/pominowner/global/util/ExceptionMessage.java
  src/main/java/com/ray/pominowner/orders/controller/dto/ReceiveOrderRequest.java
  src/main/java/com/ray/pominowner/orders/domain/OrderStatus.java
  src/main/java/com/ray/pominowner/orders/service/OrderService.java
  src/main/java/com/ray/pominowner/payment/domain/Payment.java
  src/main/java/com/ray/pominowner/payment/domain/PaymentStatus.java
  src/main/java/com/ray/pominowner/payment/dto/PaymentCreateRequest.java
  src/main/java/com/ray/pominowner/payment/service/PaymentService.java
  src/test/java/com/ray/pominowner/orders/service/OrderServiceTest.java
  src/test/java/com/ray/pominowner/payment/service/PaymentServiceTest.java
Labels: FEAT

#31 [POM-94] feat: 가게 전화번호 등록 기능 구현
  src/main/java/com/ray/pominowner/store/controller/StoreController.java
  src/main/java/com/ray/pominowner/store/controller/dto/PhoneNumberRequest.java
  src/main/java/com/ray/pominowner/store/domain/PhoneNumber.java
  src/main/java/com/ray/pominowner/store/domain/Store.java
  src/main/java/com/ray/pominowner/store/service/StoreService.java
  src/test/java/com/ray/pominowner/store/controller/StoreControllerTest.java
  src/test/java/com/ray/pominowner/store/domain/PhoneNumberTest.java
  src/test/java/com/ray/pominowner/store/domain/StoreTest.java
  src/test/java/com/ray/pominowner/store/service/StoreServiceTest.java
Labels: FEAT

#32 [POM-94] 가게 전화번호 삭제 기능 추가
  src/main/java/com/ray/pominowner/store/controller/StoreController.java
  src/main/java/com/ray/pominowner/store/domain/Store.java
  src/main/java/com/ray/pominowner/store/service/StoreService.java
  src/test/java/com/ray/pominowner/store/controller/StoreControllerTest.java
  src/test/java/com/ray/pominowner/store/domain/StoreTest.java
  src/test/java/com/ray/pominowner/store/service/StoreServiceTest.java
Labels: FEAT

#33 [POM-94] feat: 가게 정보 등록, 수정, 삭제 기능 구현
  src/main/java/com/ray/pominowner/store/controller/StoreController.java
  src/main/java/com/ray/pominowner/store/controller/dto/StoreInformationRequest.java
  src/main/java/com/ray/pominowner/store/domain/Information.java
  src/main/java/com/ray/pominowner/store/domain/Store.java
  src/main/java/com/ray/pominowner/store/service/StoreService.java
  src/test/java/com/ray/pominowner/store/controller/StoreControllerTest.java
  src/test/java/com/ray/pominowner/store/domain/InformationTest.java
  src/test/java/com/ray/pominowner/store/domain/StoreTest.java
  src/test/java/com/ray/pominowner/store/service/StoreServiceTest.java
Labels: FEAT

#34 [POM-77] 오늘의 주문 내역 조회 controller 구현, 테스트 작성
  src/main/java/com/ray/pominowner/orders/controller/OrderController.java
  src/main/java/com/ray/pominowner/orders/controller/dto/OrderResponse.java
  src/test/java/com/ray/pominowner/orders/controller/OrderControllerTest.java
Labels: FEAT

#35 feat, test: Order 엔티티에 orderedAt 필드 추가, 테스트 작성
  src/main/java/com/ray/pominowner/orders/controller/dto/ReceiveOrderRequest.java
  src/main/java/com/ray/pominowner/orders/domain/Order.java
  src/test/java/com/ray/pominowner/orders/controller/OrderControllerTest.java
  src/test/java/com/ray/pominowner/orders/service/OrderServiceDbTest.java
  src/test/java/com/ray/pominowner/orders/service/OrderServiceTest.java
Labels: FEAT

#37 [POM-84] refactor: Settlement관련 도메인 수정
  src/main/java/com/ray/pominowner/global/util/ExceptionMessage.java
  src/main/java/com/ray/pominowner/global/util/Validator.java
  src/main/java/com/ray/pominowner/payment/domain/Payment.java
  src/main/java/com/ray/pominowner/settlement/domain/DepositStatus.java
  src/main/java/com/ray/pominowner/settlement/domain/Fee.java
  src/main/java/com/ray/pominowner/settlement/domain/PayOut.java
  src/main/java/com/ray/pominowner/settlement/domain/Sales.java
  src/main/java/com/ray/pominowner/settlement/domain/Settlement.java
  src/test/java/com/ray/pominowner/settlement/domain/FeeTest.java
  src/test/java/com/ray/pominowner/settlement/domain/PayOutTest.java
  src/test/java/com/ray/pominowner/settlement/domain/SalesTest.java
  src/test/java/com/ray/pominowner/settlement/domain/SettlementTest.java
Labels: REFACTOR

#36 [POM-54] feat: 사장이 요리 완료 상태로 바꿀 수 있는 service 구현
  src/main/java/com/ray/pominowner/orders/domain/Order.java
  src/main/java/com/ray/pominowner/orders/service/OrderService.java
  src/test/java/com/ray/pominowner/orders/service/OrderServiceTest.java
Labels: FEAT

#38 [POM-94] 가게 이미지 업로드 기능 추가
  src/main/java/com/ray/pominowner/global/config/ImagePathProvider.java
  src/main/java/com/ray/pominowner/store/controller/StoreController.java
  src/main/java/com/ray/pominowner/store/domain/Store.java
  src/main/java/com/ray/pominowner/store/domain/StoreImage.java
  src/main/java/com/ray/pominowner/store/repository/StoreImageRepository.java
  src/main/java/com/ray/pominowner/store/service/StoreImageService.java
  src/main/java/com/ray/pominowner/store/service/StoreService.java
  src/main/resources/dev/application-dev.yml
  src/main/resources/store-image/empty
  src/main/resources/store-logo-image/empty
  src/test/java/com/ray/pominowner/store/controller/StoreControllerTest.java
  src/test/java/com/ray/pominowner/store/domain/StoreImageTest.java
  src/test/java/com/ray/pominowner/store/domain/StoreTest.java
  src/test/java/com/ray/pominowner/store/service/StoreImageServiceTest.java
  src/test/java/com/ray/pominowner/store/service/StoreServiceTest.java
Labels: FEAT

#39 [POM-54] feat, test: 주문 상태 요리 완료로 변경 controller 구현, 테스트 작성
  src/main/java/com/ray/pominowner/orders/controller/OrderController.java
  src/main/java/com/ray/pominowner/orders/service/OrderService.java
  src/test/java/com/ray/pominowner/orders/controller/OrderControllerTest.java
Labels: FEAT

#40 [POM-84] feat: 정산 생성 기능 구현
  src/main/java/com/ray/pominowner/orders/controller/OrderController.java
  src/main/java/com/ray/pominowner/orders/controller/dto/ReceiveOrderRequest.java
  src/main/java/com/ray/pominowner/orders/service/OrderProcessingService.java
  src/main/java/com/ray/pominowner/settlement/domain/Settlement.java
  src/main/java/com/ray/pominowner/settlement/repository/SettlementRepository.java
  src/main/java/com/ray/pominowner/settlement/service/SettlementService.java
  src/test/java/com/ray/pominowner/orders/controller/OrderControllerTest.java
  src/test/java/com/ray/pominowner/orders/service/OrderProcessingServiceTest.java
  src/test/java/com/ray/pominowner/settlement/domain/SettlementTest.java
  src/test/java/com/ray/pominowner/settlement/service/SettlementServiceTest.java
Labels: FEAT

#43 [POM-94] feat: image 관련 mappedSuperclass로 분리, menu 도메인 엔티티 validation 및 전체적 구조 설정
  src/main/java/com/ray/pominowner/global/domain/BaseFileEntity.java
  src/main/java/com/ray/pominowner/menu/controller/MenuController.java
  src/main/java/com/ray/pominowner/menu/controller/dto/MenuInfoRequest.java
  src/main/java/com/ray/pominowner/menu/domain/Menu.java
  src/main/java/com/ray/pominowner/menu/domain/MenuImage.java
  src/main/java/com/ray/pominowner/menu/repository/MenuRepository.java
  src/main/java/com/ray/pominowner/menu/service/MenuService.java
  src/main/java/com/ray/pominowner/store/domain/StoreImage.java
Labels: FEAT

#42 [POM-84] test: 중복된 엔티티 객체 생성 코드 분리
  src/test/java/com/ray/pominowner/settlement/SettlementTestFixture.java
  src/test/java/com/ray/pominowner/settlement/domain/FeeTest.java
  src/test/java/com/ray/pominowner/settlement/domain/PayOutTest.java
  src/test/java/com/ray/pominowner/settlement/domain/SalesTest.java
  src/test/java/com/ray/pominowner/settlement/domain/SettlementTest.java
  src/test/java/com/ray/pominowner/settlement/service/SettlementServiceTest.java
Labels: TEST

#45 [POM-81] feat: 사장이 주문 수락 시 예상 대기 시간을 설정할 수 있다
  src/main/java/com/ray/pominowner/orders/controller/OrderController.java
  src/main/java/com/ray/pominowner/orders/controller/dto/ApproveOrderRequest.java
  src/main/java/com/ray/pominowner/orders/service/OrderService.java
  src/test/java/com/ray/pominowner/orders/controller/OrderControllerTest.java
  src/test/java/com/ray/pominowner/orders/service/OrderServiceTest.java
Labels: FEAT

#46 [POM-93] 주문 정보에 따른 정산 조회 기능 구현
  src/main/java/com/ray/pominowner/global/util/ExceptionMessage.java
  src/main/java/com/ray/pominowner/orders/domain/Order.java
  src/main/java/com/ray/pominowner/settlement/controller/SettlementController.java
  src/main/java/com/ray/pominowner/settlement/controller/dto/SettlementResponse.java
  src/main/java/com/ray/pominowner/settlement/domain/Fee.java
  src/main/java/com/ray/pominowner/settlement/domain/Settlement.java
  src/main/java/com/ray/pominowner/settlement/repository/SettlementRepository.java
  src/main/java/com/ray/pominowner/settlement/service/SettlementService.java
  src/test/java/com/ray/pominowner/settlement/service/SettlementServiceTest.java
Labels: FEAT

#47 [POM-80] feat: 메뉴 등록 및 수정 기능 구현
  src/main/java/com/ray/pominowner/global/util/ExceptionMessage.java
  src/main/java/com/ray/pominowner/menu/controller/MenuController.java
  src/main/java/com/ray/pominowner/menu/controller/dto/MenuRequest.java
  src/main/java/com/ray/pominowner/menu/domain/Menu.java
  src/main/java/com/ray/pominowner/menu/repository/MenuImageRepository.java
  src/main/java/com/ray/pominowner/menu/service/MenuImageService.java
  src/main/java/com/ray/pominowner/menu/service/MenuService.java
  src/test/java/com/ray/pominowner/menu/controller/MenuControllerTest.java
Labels: FEAT

#48 [POM-81] feat: 사장님이 설정한 대기 시간 고객측 서버로 전달
  src/main/java/com/ray/pominowner/orders/service/OrderService.java
  src/main/java/com/ray/pominowner/orders/service/RestTemplateServiceProvider.java
  src/main/java/com/ray/pominowner/orders/service/dto/ApproveOrderNotifyRequest.java
  src/test/java/com/ray/pominowner/orders/service/OrderServiceTest.java
Labels: FEAT

#49 [POM-76] feat: 일 정산 조회 기능 구현
  src/main/java/com/ray/pominowner/global/util/ExceptionMessage.java
  src/main/java/com/ray/pominowner/orders/controller/dto/ReceiveOrderRequest.java
  src/main/java/com/ray/pominowner/settlement/controller/SettlementController.java
  src/main/java/com/ray/pominowner/settlement/controller/vo/SettlementByStoreRequest.java
  src/main/java/com/ray/pominowner/settlement/domain/ServiceType.java
  src/main/java/com/ray/pominowner/settlement/domain/Settlement.java
  src/main/java/com/ray/pominowner/settlement/repository/SettlementRepository.java
  src/main/java/com/ray/pominowner/settlement/service/DateType.java
  src/main/java/com/ray/pominowner/settlement/service/SettlementService.java
  src/test/java/com/ray/pominowner/settlement/SettlementTestFixture.java
  src/test/java/com/ray/pominowner/settlement/domain/SettlementTest.java
  src/test/java/com/ray/pominowner/settlement/service/SettlementServiceTest.java
Labels: FEAT

#50 [POM-81] feat: restTemplate 에러 핸들러 구현 및 적용
  src/main/java/com/ray/pominowner/orders/service/RestTemplateResponseErrorHandler.java
  src/main/java/com/ray/pominowner/orders/service/RestTemplateServiceProvider.java
Labels: FEAT

#51 [POM-80] 옵션 도메인 로직 작성 및 테스트
  src/main/java/com/ray/pominowner/menu/domain/Option.java
  src/main/java/com/ray/pominowner/menu/domain/OptionGroup.java
  src/test/java/com/ray/pominowner/menu/domain/OptionTest.java
Labels: FEAT

#52 [POM-76] feat: 일 정산 service 계산 로직 상세 구현
  src/main/java/com/ray/pominowner/settlement/controller/DailySettlementResponseConverter.java
  src/main/java/com/ray/pominowner/settlement/controller/SettlementController.java
  src/main/java/com/ray/pominowner/settlement/controller/dto/DailySettlementResponse.java
  src/main/java/com/ray/pominowner/settlement/controller/vo/SettlementByStoreRequest.java
  src/main/java/com/ray/pominowner/settlement/domain/PayOut.java
  src/main/java/com/ray/pominowner/settlement/domain/Settlement.java
  src/main/java/com/ray/pominowner/settlement/service/DateType.java
  src/main/java/com/ray/pominowner/settlement/service/SettlementService.java
  src/main/java/com/ray/pominowner/settlement/service/vo/SettlementByStoreRequest.java
  src/test/java/com/ray/pominowner/settlement/domain/PayOutTest.java
Labels: FEAT

#53 [POM-80] feat: 옵션 그룹 및 옵션 등록 전체적인 구조 추가 및 도메인 로직 추가
  src/main/java/com/ray/pominowner/menu/controller/OptionController.java
  src/main/java/com/ray/pominowner/menu/controller/OptionGroupController.java
  src/main/java/com/ray/pominowner/menu/controller/dto/OptionGroupRequest.java
  src/main/java/com/ray/pominowner/menu/controller/dto/OptionRequest.java
  src/main/java/com/ray/pominowner/menu/domain/OptionGroup.java
  src/main/java/com/ray/pominowner/menu/repository/OptionGroupRepository.java
  src/main/java/com/ray/pominowner/menu/service/OptionGroupService.java
  src/main/java/com/ray/pominowner/menu/service/OptionService.java
  src/test/java/com/ray/pominowner/menu/domain/OptionTest.java
Labels: FEAT

#56 [POM-76] test: 일 정산 조회 테스트 코드 작성
  src/main/java/com/ray/pominowner/settlement/controller/dto/DailySettlementResponse.java
  src/main/java/com/ray/pominowner/settlement/domain/Settlement.java
  src/main/java/com/ray/pominowner/settlement/service/DateType.java
  src/test/java/com/ray/pominowner/settlement/controller/SettlementControllerTest.java
  src/test/java/com/ray/pominowner/settlement/repository/SettlementRepositoryTest.java
  src/test/java/com/ray/pominowner/settlement/service/SettlementServiceTest.java
Labels: TEST

#58 [POM-80] feat: OptionGroup crud 기능 구현
  src/main/java/com/ray/pominowner/menu/controller/OptionGroupController.java
  src/main/java/com/ray/pominowner/menu/controller/dto/OptionGroupUpdateRequest.java
  src/main/java/com/ray/pominowner/menu/service/OptionGroupService.java
  src/main/java/com/ray/pominowner/menu/service/vo/OptionGroupUpdateInfo.java
  src/test/java/com/ray/pominowner/menu/controller/OptionGroupControllerTest.java
Labels: FEAT

#55 [POM-80] feat: 옵션 등록 기능 구현
  src/main/java/com/ray/pominowner/menu/controller/OptionController.java
  src/main/java/com/ray/pominowner/menu/controller/OptionGroupController.java
  src/main/java/com/ray/pominowner/menu/controller/dto/OptionGroupUpdateRequest.java
  src/main/java/com/ray/pominowner/menu/controller/dto/OptionGroupWithOptionResponse.java
  src/main/java/com/ray/pominowner/menu/controller/dto/OptionRequest.java
  src/main/java/com/ray/pominowner/menu/controller/dto/OptionResponse.java
  src/main/java/com/ray/pominowner/menu/controller/dto/OptionUpdateRequest.java
  src/main/java/com/ray/pominowner/menu/domain/Option.java
  src/main/java/com/ray/pominowner/menu/domain/OptionGroup.java
  src/main/java/com/ray/pominowner/menu/repository/OptionRepository.java
  src/main/java/com/ray/pominowner/menu/service/OptionGroupService.java
  src/main/java/com/ray/pominowner/menu/service/OptionService.java
  src/main/java/com/ray/pominowner/menu/service/vo/OptionGroupUpdateInfo.java
  src/main/java/com/ray/pominowner/menu/service/vo/OptionUpdateInfo.java
  src/test/java/com/ray/pominowner/menu/controller/OptionControllerTest.java
  src/test/java/com/ray/pominowner/menu/controller/OptionGroupControllerTest.java
Labels: FEAT

#63 [POM-125] feat: 모든 컨트롤러 Spring Rest Docs 적용
  src/main/java/com/ray/pominowner/menu/controller/OptionController.java
  src/main/java/com/ray/pominowner/menu/controller/OptionGroupController.java
  src/main/java/com/ray/pominowner/menu/controller/dto/OptionGroupUpdateRequest.java
  src/main/java/com/ray/pominowner/menu/controller/dto/OptionGroupWithOptionResponse.java
  src/main/java/com/ray/pominowner/menu/controller/dto/OptionUpdateRequest.java
  src/main/java/com/ray/pominowner/menu/service/OptionGroupService.java
  src/main/java/com/ray/pominowner/menu/service/OptionService.java
  src/main/java/com/ray/pominowner/menu/service/vo/OptionGroupUpdateInfo.java
  src/main/java/com/ray/pominowner/menu/service/vo/OptionUpdateInfo.java
  src/main/java/com/ray/pominowner/store/domain/BusinessHour.java
  src/test/java/com/ray/pominowner/menu/controller/MenuControllerTest.java
  src/test/java/com/ray/pominowner/menu/controller/OptionControllerTest.java
  src/test/java/com/ray/pominowner/menu/controller/OptionGroupControllerTest.java
  src/test/java/com/ray/pominowner/store/controller/StoreControllerTest.java
Labels: FEAT

#64 [POM-125] feat: spring rest docs index.adoc 작성
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/index.html
  src/test/java/com/ray/pominowner/orders/controller/OrderControllerTest.java
  src/test/java/com/ray/pominowner/settlement/controller/SettlementControllerTest.java
Labels: FEAT
